import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio Landing Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='logo.jpg' />
      </Head>
      <Hero heading='Hi. This is KCWIN' message='As a a graphic, UXUI, and motion designer, I create designs that combine aesthetics with effective problem-solving and idea communication.' />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  );
}
